version: "3"

services:
  node:
    image: "node:lts-alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./server/:/home/node/app
    command: ash -c "npm i && node index.js"
    networks:
      - traefik-public
    ports:
      - "3000:3000"
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.snapdrop.rule: Host(`drop.surpuissant.com`)
      traefik.http.routers.snapdrop.entrypoints: websecure
      traefik.http.routers.snapdrop.tls.certresolver: "letsencrypt"
      #traefik.http.services.snapdrop.loadbalancer.server.port: 3000

networks:
  traefik-public:
    external: true
