version: "3"

services:
  snapdrop:
    image: lscr.io/linuxserver/snapdrop:latest
    container_name: snapdrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./:/config
    networks:
      - traefik-public
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.snapdrop.rule: Host(`drop.surpuissant.com`)
      traefik.http.routers.snapdrop.entrypoints: websecure
      traefik.http.routers.snapdrop.tls.certresolver: "letsencrypt"
      traefik.http.services.snapdrop.loadbalancer.server.port: 3000

networks:
  traefik-public:
    external: true
