version: "3"
services:
  node:
    image: "node:lts-alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./server/:/home/node/app
    command: ash -c "npm i && node index.js"
    labels:
      traefik.enable: true
      traefik.http.routers.drop.rule: Host(`drop.surpuissant.com`)
      traefik.http.routers.drop.entrypoints: websecure
      traefik.http.routers.drop.tls.certresolver: "letsencrypt"
      traefik.http.services.drop.loadbalancer.server.port: 3000
