version: "3"
services:
  node:
    image: "node:lts-alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./server/:/home/node/app
    command: ash -c "npm i && node index.js"
    ports:
      - '3000:3001'
    labels:
      traefik.enable: true
      traefik.http.routers.drop.rule: Host(`drop.surpuissant.com`)
      traefik.http.routers.drop.entrypoints: websecure
      traefik.http.routers.drop.tls.certresolver: "letsencrypt"
