version: "3"

# For example, -p 8080:80 would expose port 80 from inside the container to be accessible from the host's IP on port 8080 outside the container.

services:
  node:
    image: "node:lts-alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./server/:/home/node/app
    command: ash -c "npm i && node index.js"
    networks:
      - snapdrop

  nginx:
    build:
      context: ./docker/
      dockerfile: nginx-with-openssl.Dockerfile
    image: "nginx-with-openssl"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certs:/etc/ssl/certs
      - ./docker/openssl:/mnt/openssl
    #ports:
      #- "3000:80"
      #- "3001:443"
    env_file: ./docker/fqdn.env
    entrypoint: /mnt/openssl/create.sh
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - traefik-public
      - snapdrop
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.snapdrop.rule: Host(`drop.surpuissant.com`)
      traefik.http.routers.snapdrop.entrypoints: websecure
      traefik.http.routers.snapdrop.tls.certresolver: "letsencrypt"
      traefik.http.services.snapdrop.loadbalancer.server.port: 1443

networks:
  snapdrop:
    driver: bridge
  traefik-public:
    external: true
